include:
  - component: $CI_SERVER_FQDN/sv/taskfiles/mise@2.2.0

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  script: task -t ./Deploy.yml deploy

shutdown:
  stage: deploy
  when: manual
  allow_failure: false
  script: task -t ./Deploy.yml shutdown
