version: '3.8'

services:
  app:
    image: registry.s-v.de/tihav/wiki
    restart: unless-stopped
    env_file: env
    ports:
      - "8080:8080"
    volumes:
      - wiki_data:/app/app/data

volumes:
  wiki_data:
    driver: local