version: '3.8'

services:
  wiki:
    image: registry.s-v.de/tihav/wiki
    container_name: wiki
    ports:
      - "8080:8080"
    volumes:
      - wiki_data:/app/app/data
    restart: unless-stopped

volumes:
  wiki_data:
    driver: local