/**
 * GET /api/v1/auth/cli
 *
 * Browser-based CLI login. Requires an active user session (browser cookie).
 * Validates that redirect_uri is a localhost callback, generates a short-lived
 * one-time code, and redirects back to the CLI's local server.
 *
 * Query params:
 *   redirect_uri  must be http://localhost:<port>/callback or http://127.0.0.1:<port>/callback
 *   state         random value generated by the CLI; echoed back for CSRF protection
 */

import type { APIRoute } from "astro";
import { randomBytes } from "node:crypto";
import { badRequestResponse, requireUser, withApiErrorHandling } from "#db/api.ts";
import { listUserSpaces } from "#db/spaces.ts";

// One-time codes: code → { userId, spaceId, expiresAt }
export const pendingCliCodes = new Map<string, { userId: string; spaceId: string; expiresAt: number }>();

const CODE_TTL_MS = 60_000;

function isLocalhostUri(uri: string): boolean {
  try {
    const url = new URL(uri);
    return (
      url.protocol === "http:" &&
      (url.hostname === "localhost" || url.hostname === "127.0.0.1") &&
      url.pathname === "/callback"
    );
  } catch {
    return false;
  }
}

export const GET: APIRoute = (context) =>
  withApiErrorHandling(async () => {
    const user = requireUser(context);

    const redirectUri = context.url.searchParams.get("redirect_uri");
    const state = context.url.searchParams.get("state");

    if (!redirectUri || !isLocalhostUri(redirectUri)) {
      throw badRequestResponse("redirect_uri must be http://localhost:<port>/callback");
    }
    if (!state || state.length < 16) {
      throw badRequestResponse("state is required and must be at least 16 characters");
    }

    // Pick the user's first space.
    const spaces = await listUserSpaces(user.id);
    if (spaces.length === 0) {
      const url = new URL(redirectUri);
      url.searchParams.set("error", "no_spaces");
      url.searchParams.set("state", state);
      return Response.redirect(url.toString(), 302);
    }
    const spaceId = spaces[0].id;

    // Mint a one-time code.
    const code = randomBytes(32).toString("hex");
    pendingCliCodes.set(code, { userId: user.id, spaceId, expiresAt: Date.now() + CODE_TTL_MS });

    // Expire the code automatically.
    setTimeout(() => pendingCliCodes.delete(code), CODE_TTL_MS);

    const callbackUrl = new URL(redirectUri);
    callbackUrl.searchParams.set("code", code);
    callbackUrl.searchParams.set("state", state);
    callbackUrl.searchParams.set("space", spaceId);

    return Response.redirect(callbackUrl.toString(), 302);
  }, "CLI auth failed");
