/** Build the native embedding runtime and generate its static Bun loader. */

import { existsSync } from "node:fs";
import { copyFile, mkdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { $ } from "bun";

const here = import.meta.dir;
const outDir = join(here, "../../src/embeddings/native");
const modelDir = join(here, "models");
const args = process.argv.slice(2);
const debug = args.includes("--debug");

function flagValue(name: string): string | undefined {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : undefined;
}

const rustTarget = flagValue("--target");
const destPlatform = flagValue("--dest-platform") ?? process.platform;
const destArch = flagValue("--dest-arch") ?? process.arch;
const buildDirName = "generated";
const buildDir = join(here, buildDirName);
await mkdir(buildDir, { recursive: true });

const modelRevision = "c32e6154d1bb7a0e47c5e745fd895e7700f44385";
const modelBaseUrl = `https://huggingface.co/Qdrant/bge-small-en-v1.5-onnx-Q/resolve/${modelRevision}`;
const modelFiles = [
  "config.json",
  "model_optimized.onnx",
  "special_tokens_map.json",
  "tokenizer.json",
  "tokenizer_config.json",
];

async function downloadEmbeddedModel() {
  await mkdir(modelDir, { recursive: true });

  for (const filename of modelFiles) {
    const destination = join(modelDir, filename);
    if (existsSync(destination)) continue;

    console.log(`[native-embedding] downloading ${filename}`);
    const response = await fetch(`${modelBaseUrl}/${filename}`);
    if (!response.ok) {
      throw new Error(
        `[native-embedding] failed to download ${filename}: ${response.status} ${response.statusText}`,
      );
    }

    const temporary = `${destination}.part`;
    await writeFile(temporary, new Uint8Array(await response.arrayBuffer()));
    await rename(temporary, destination);
  }
}

await downloadEmbeddedModel();

const napiArgs = ["build", "--output-dir", buildDirName, "--no-js"];
if (!debug) napiArgs.push("--release");
if (rustTarget) napiArgs.push("--target", rustTarget);

console.log(`[native-embedding] napi ${napiArgs.join(" ")}`);
await $`bunx napi ${napiArgs}`.cwd(here);

const built = join(buildDir, "embedding.node");
if (!existsSync(built)) {
  throw new Error(`[native-embedding] expected build output not found at ${built}`);
}

const destName = `embedding-${destPlatform}-${destArch}.node`;
const dest = join(outDir, destName);
await mkdir(dirname(dest), { recursive: true });
await rm(dest, { force: true });
await copyFile(built, dest);
console.log(`[native-embedding] → ${dest}`);

await writeFile(
  join(outDir, "addon.ts"),
  `// Generated by native/embedding/build.ts — do not edit.\nexport const nativeEmbedding = require("./${destName}");\n`,
);
