import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

const appDir = join(import.meta.dir);
const clientDir = join(appDir, "dist/client");
const outputFile = join(appDir, "generated/client-assets.ts");

export async function collectClientAssetFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name.startsWith(".")) {
      continue;
    }

    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectClientAssetFiles(fullPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files;
}

export async function generateClientAssetsModule() {
  try {
    await readdir(clientDir);
  } catch {
    throw new Error(`Client build output not found at ${clientDir}`);
  }

  const files = (await collectClientAssetFiles(clientDir)).sort();
  const importLines: string[] = [];
  const mapEntries: string[] = [];

  for (const [index, filePath] of files.entries()) {
    const importName = `asset${index}`;
    const importPath = relative(dirname(outputFile), filePath).split(sep).join("/");
    const publicPath = `/${relative(clientDir, filePath).split(sep).join("/")}`;

    importLines.push(`import ${importName} from "${importPath}" with { type: "file" };`);
    mapEntries.push(`  ["${publicPath}", ${importName}]`);
  }

  const content = [
    "// Generated by build.ts. Do not edit.",
    ...importLines,
    "",
    "export const embeddedClientAssets = new Map<string, string>([",
    ...mapEntries.map((entry) => `${entry},`),
    "]);",
    "",
  ].join("\n");

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, content);
}

await generateClientAssetsModule();

/**
 * Compile vektor.ts into a portable single-file executable.
 *
 * @img/sharp-wasm32 loads its WASM binary via fs.readFileSync(__dirname +
 * "/sharp-wasm32-*.wasm"). Bun doesn't auto-embed files referenced that way,
 * so we use a plugin that:
 *  1. Intercepts the @img/sharp-wasm32/sharp.node import.
 *  2. Generates a wrapper that imports the .wasm file with { type: "file" }
 *     (causing bun to embed it) and patches Module.locateFile so the
 *     emscripten runtime reads it from the embedded $bunfs path.
 */
import { createRequire } from "node:module";
import { existsSync, readFileSync } from "node:fs";
import { dirname as pathDirname } from "node:path";

const _require = createRequire(import.meta.url);
const wasmPkgJsonPath = _require.resolve("@img/sharp-wasm32/package.json");
const wasmPkgDir = pathDirname(wasmPkgJsonPath);
const wasmPkgVersion = (_require(wasmPkgJsonPath) as { version: string }).version;
const wasmJsPath = `${wasmPkgDir}/lib/sharp-wasm32-${wasmPkgVersion}.node.js`;
const wasmBinPath = `${wasmPkgDir}/lib/sharp-wasm32-${wasmPkgVersion}.node.wasm`;

if (!existsSync(wasmJsPath) || !existsSync(wasmBinPath)) {
  throw new Error(`[sharp-wasm32] could not find wasm files at ${wasmPkgDir}/lib/`);
}

console.log(`[sharp-wasm32] embedding ${wasmBinPath}`);

const sharpWasmPlugin: import("bun").BunPlugin = {
  name: "sharp-wasm32-embed",
  setup(build) {
    // Intercept @img/sharp-wasm32/sharp.node (the exports-map entry point)
    build.onResolve({ filter: /@img\/sharp-wasm32/ }, () => ({
      path: wasmJsPath,
      namespace: "sharp-wasm32",
    }));

    build.onLoad({ filter: /.*/, namespace: "sharp-wasm32" }, () => ({
      // Wrap the emscripten JS so that:
      //  - The .wasm file is imported with { type: "file" } → bun embeds it.
      //  - Module.locateFile is patched to return the embedded $bunfs path
      //    instead of the __dirname-relative path that no longer exists.
      contents: `
import wasmPath from ${JSON.stringify(wasmBinPath)} with { type: "file" };
// var (not const/let) so the emscripten "typeof Module !== 'undefined'" check
// below sees this object and inherits our locateFile patch.
var Module = {
  locateFile(name, dir) {
    if (name.endsWith(".wasm")) return wasmPath;
    return dir + name;
  },
};
${readFileSync(wasmJsPath, "utf-8")}
`,
      loader: "js",
    }));
  },
};

const result = await Bun.build({
  entrypoints: ["./vektor.ts"],
  // @ts-ignore — Bun.build compile option
  compile: true,
  outfile: "./vektor",
  plugins: [sharpWasmPlugin],
  // lightningcss bundles a Rust-compiled native binary (../pkg) that bun
  // cannot resolve. It's pulled in transitively by Astro's SSR output but
  // is not actually used at runtime — marking it external skips bundling it.
  external: ["lightningcss"],
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

console.log(`[compile] ${result.outputs[0]?.path}`);
