import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

const appDir = join(import.meta.dir);
const clientDir = join(appDir, "dist/client");
const outputFile = join(appDir, "generated/client-assets.ts");

export async function collectClientAssetFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name.startsWith(".")) {
      continue;
    }

    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectClientAssetFiles(fullPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files;
}

export async function generateClientAssetsModule() {
  try {
    await readdir(clientDir);
  } catch {
    throw new Error(`Client build output not found at ${clientDir}`);
  }

  const files = (await collectClientAssetFiles(clientDir)).sort();
  const importLines: string[] = [];
  const mapEntries: string[] = [];

  for (const [index, filePath] of files.entries()) {
    const importName = `asset${index}`;
    const importPath = relative(dirname(outputFile), filePath).split(sep).join("/");
    const publicPath = `/${relative(clientDir, filePath).split(sep).join("/")}`;

    importLines.push(`import ${importName} from "${importPath}" with { type: "file" };`);
    mapEntries.push(`  ["${publicPath}", ${importName}]`);
  }

  const content = [
    "// Generated by build.ts. Do not edit.",
    // `with { type: "file" }` makes Bun resolve these imports to file path
    // strings at runtime, but TypeScript still tries to type-check the
    // referenced build output as a real JS module, which doesn't match.
    "// @ts-nocheck",
    ...importLines,
    "",
    "export const embeddedClientAssets = new Map<string, string>([",
    ...mapEntries.map((entry) => `${entry},`),
    "]);",
    "",
  ].join("\n");

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, content);
}

await generateClientAssetsModule();

// Patch dist/server/entry.mjs so resolveClientDir works inside the compiled
// Bun binary. @astrojs/node@11 walks up from import.meta.url looking for a
// "server" path segment, which doesn't exist when bundled (import.meta.url
// becomes "file:///$bunfs/root/vektor.js"). Since options.client already
// holds the absolute URL of the client dir, we use it directly. The resolved
// path is only used to serve pre-rendered error pages (404/500.html), which
// don't exist in SSR mode, so a build-machine path is fine in all cases.
{
  const entryMjs = join(appDir, "dist/server/entry.mjs");
  let src = await readFile(entryMjs, "utf-8");
  // Replace the whole function by matching from its declaration to the
  // //#endregion comment that follows it (avoids fragile nested-brace counting).
  src = src.replace(
    /function resolveClientDir\(options\)\s*\{[\s\S]*?\n\/\/#endregion/,
    `function resolveClientDir(options) { return url.fileURLToPath(new URL(options.client)); }\n//#endregion`,
  );
  await writeFile(entryMjs, src, "utf-8");
  console.log("[patch] patched resolveClientDir in dist/server/entry.mjs");
}

import { existsSync } from "node:fs";

/**
 * Compile vektor.ts into a portable single-file executable.
 *
 * Image transforms and JavaScript execution are provided by native Rust N-API
 * addons under native/image and native/exec.
 * Bun auto-embeds .node addons referenced by a static `require`; each native
 * build generates a platform-specific loader that the application imports.
 *
 * Cross-target release builds compile per native runner; see
 * .github/workflows/release.yml.
 */
const addonFilename = `image-${process.platform}-${process.arch}.node`;
const addonPath = `${import.meta.dir}/src/files/native/${addonFilename}`;
if (!existsSync(addonPath)) {
  throw new Error(
    `[native-image] addon not found at ${addonPath}\n` +
      `Build it first:  cd native/image && bun run build`,
  );
}

const shimPath = `${import.meta.dir}/src/files/native/addon.ts`;
if (!existsSync(shimPath)) {
  throw new Error(
    `[native-image] shim not found at ${shimPath}\n` +
      `Build it first:  cd native/image && bun run build`,
  );
}
console.log(`[native-image] embedding ${addonFilename}`);

const execAddonFilename = `exec-${process.platform}-${process.arch}.node`;
const execAddonPath = `${import.meta.dir}/src/exec/native/${execAddonFilename}`;
if (!existsSync(execAddonPath)) {
  throw new Error(
    `[native-exec] addon not found at ${execAddonPath}\n` +
      `Build it first:  cd native/exec && bun run build`,
  );
}
const execShimPath = `${import.meta.dir}/src/exec/native/addon.ts`;
if (!existsSync(execShimPath)) {
  throw new Error(
    `[native-exec] shim not found at ${execShimPath}\n` +
      `Build it first:  cd native/exec && bun run build`,
  );
}
console.log(`[native-exec] embedding ${execAddonFilename}`);

const embeddingAddonFilename = `embedding-${process.platform}-${process.arch}.node`;
const embeddingAddonPath = `${import.meta.dir}/src/embeddings/native/${embeddingAddonFilename}`;
if (!existsSync(embeddingAddonPath)) {
  throw new Error(
    `[native-embedding] addon not found at ${embeddingAddonPath}\n` +
      `Build it first:  cd native/embedding && bun run build`,
  );
}
const embeddingShimPath = `${import.meta.dir}/src/embeddings/native/addon.ts`;
if (!existsSync(embeddingShimPath)) {
  throw new Error(
    `[native-embedding] shim not found at ${embeddingShimPath}\n` +
      `Build it first:  cd native/embedding && bun run build`,
  );
}
console.log(`[native-embedding] embedding ${embeddingAddonFilename}`);

const result = await Bun.build({
  entrypoints: ["./vektor.ts"],
  compile: true,
  // @ts-expect-error — `outfile` is valid alongside `compile` at runtime (see
  // Bun.build's own docs), but tsgo's bundled bun-types doesn't reflect it.
  outfile: "./vektor",
  // lightningcss bundles a Rust-compiled native binary (../pkg) that bun
  // cannot resolve. It's pulled in transitively by Astro's SSR output but
  // is not actually used at runtime — marking it external skips bundling it.
  external: ["lightningcss"],
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

console.log(`[compile] ${result.outputs[0]?.path}`);
