<script setup lang="ts">
import {
  activityIcon,
  addIcon,
  agentChatIcon,
  archiveDocumentIcon,
  boldIcon,
  cancelIcon,
  categoryIcon,
  chevronDownIcon,
  collapseSidebarIcon,
  confirmationIcon,
  contextMenuMoreIcon,
  dateIcon,
  deleteElementIcon,
  downloadIcon,
  editDocumentIcon,
  enableNotificationsIcon,
  folderIcon,
  fourColumnsIcon,
  headerImageIcon,
  homeIcon,
  imageIcon,
  indentIcon,
  italicIcon,
  justifyBlockIcon,
  justifyCenterIcon,
  justifyLeftIcon,
  justifyRightIcon,
  linkIcon,
  listIcon,
  muteNotificationsIcon,
  numberedListIcon,
  outdentIcon,
  pinToHomeIcon,
  printIcon,
  publishIcon,
  redoIcon,
  searchIcon,
  sendMessageIcon,
  settingsIcon,
  sourceCodeIcon,
  strikeThroughIcon,
  taskListIcon,
  textColorIcon,
  threeColumnsIcon,
  twoColumnsIcon,
  underlineIcon,
  undoIcon,
  uploadFileIcon,
} from "#assets/icons.ts";

const icons = {
  placeholder: homeIcon,
  home: homeIcon,
  search: searchIcon,
  edit: editDocumentIcon,
  "enable-notifications": enableNotificationsIcon,
  folder: folderIcon,
  plus: addIcon,
  confirmation: confirmationIcon,
  cancel: cancelIcon,
  trash: deleteElementIcon,
  settings: settingsIcon,
  download: downloadIcon,
  image: imageIcon,
  "header-image": headerImageIcon,
  print: printIcon,
  publish: publishIcon,
  history: activityIcon,
  "source-code": sourceCodeIcon,
  collapse: collapseSidebarIcon,
  more: contextMenuMoreIcon,
  calendar: dateIcon,
  archive: archiveDocumentIcon,
  category: categoryIcon,
  "columns-2": twoColumnsIcon,
  "columns-3": threeColumnsIcon,
  "columns-4": fourColumnsIcon,
  pin: pinToHomeIcon,
  "pin-filled": pinToHomeIcon,
  bold: boldIcon,
  italic: italicIcon,
  underline: underlineIcon,
  strikethrough: strikeThroughIcon,
  "align-left": justifyLeftIcon,
  "align-center": justifyCenterIcon,
  "align-right": justifyRightIcon,
  "align-justify": justifyBlockIcon,
  send: sendMessageIcon,
  link: linkIcon,
  "chevron-down": chevronDownIcon,
  "list-ordered": numberedListIcon,
  "list-unordered": listIcon,
  "list-check": taskListIcon,
  "mute-notifications": muteNotificationsIcon,
  "text-color": textColorIcon,
  undo: undoIcon,
  upload: uploadFileIcon,
  redo: redoIcon,
  indent: indentIcon,
  outdent: outdentIcon,
  "agent-chat": agentChatIcon,
};

const props = defineProps<{
  name: keyof typeof icons;
}>();
</script>

<template>
  <div
    v-html="icons[props.name]"
    class="icon flex-none aspect-square [&_svg]:w-full [&_svg]:h-full"
    aria-hidden="true"
  />
</template>
