/**
 * Build the native image addon and place the resulting `.node` where the app
 * can embed it.
 *
 * Output: app/src/files/native/image-<platform>-<arch>.node
 *
 * Cross-compilation: pass --target <rust-triple> --dest-platform <bun-platform>
 * (e.g. on a linux runner you only build linux; darwin is built on a macOS
 * runner — see .github/workflows/release.yml).
 */

import { existsSync } from "node:fs";
import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { $ } from "bun";

const here = import.meta.dir;
const outDir = join(here, "../../src/files/native");

const args = process.argv.slice(2);
const debug = args.includes("--debug");

function flagValue(name: string): string | undefined {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}

const rustTarget = flagValue("--target"); // e.g. x86_64-unknown-linux-gnu
// Bun's process.platform/arch naming, defaulting to the host.
const destPlatform = flagValue("--dest-platform") ?? process.platform;
const destArch = flagValue("--dest-arch") ?? process.arch;

// napi resolves the output dir relative to cwd (`here`); keep it relative to
// avoid the path being doubled.
const buildDirName = "generated";
const buildDir = join(here, buildDirName);
await mkdir(buildDir, { recursive: true });

const napiArgs = ["build", buildDirName, "--js", "false"];
if (!debug) napiArgs.push("--release");
if (rustTarget) napiArgs.push("--target", rustTarget);

console.log(`[native-image] napi ${napiArgs.join(" ")}`);
await $`bunx napi ${napiArgs}`.cwd(here);

// napi emits `<napi.name>.node` → "image.node"
const built = join(buildDir, "image.node");
if (!existsSync(built)) {
  throw new Error(`[native-image] expected build output not found at ${built}`);
}

const destName = `image-${destPlatform}-${destArch}.node`;
const dest = join(outDir, destName);
await mkdir(dirname(dest), { recursive: true });
await rm(dest, { force: true });
await copyFile(built, dest);

console.log(`[native-image] → ${dest}`);

// Write the dev/compile shim so both `bun run` and `bun build --compile` can
// load the addon via a static require() that Bun's bundler can trace.
const shimPath = join(outDir, "addon.ts");
await writeFile(
  shimPath,
  `// Generated by native/image/build.ts — do not edit.\nexport default require("./${destName}");\n`,
);
