#!/usr/bin/env bun
/**
 * Generates a static route manifest for the Express-served API.
 *
 * Scans `app/src/api/routes/**` and derives an Astro-style URL pattern from
 * each file's path (e.g. `v1/spaces/[spaceId]/index.ts` -> `/api/v1/spaces/[spaceId]`),
 * then emits `app/src/api/routes.generated.ts` with static imports so the
 * manifest is bundled into the compiled `vektor` binary.
 *
 * Run via `bun run scripts/genApiRoutes.ts` (also wired into the build task).
 */
import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const appDir = join(import.meta.dir, "..", "app");
const routesDir = join(appDir, "src", "api", "routes");
const outputFile = join(appDir, "src", "api", "routes.generated.ts");

async function collectRouteFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectRouteFiles(fullPath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".ts")) {
      files.push(fullPath);
    }
  }

  return files;
}

/** Derive the Astro-style URL pattern from a route file path. */
function patternForFile(filePath: string): string {
  const rel = relative(routesDir, filePath).split(sep).join("/");
  const withoutExt = rel.replace(/\.ts$/, "");
  const segments = withoutExt.split("/");
  if (segments[segments.length - 1] === "index") {
    segments.pop();
  }
  return `/api/${segments.join("/")}`.replace(/\/$/, "") || "/api";
}

async function main() {
  const files = (await collectRouteFiles(routesDir)).sort();

  const importLines: string[] = [];
  const entries: string[] = [];

  files.forEach((filePath, index) => {
    const importName = `route${index}`;
    const importPath = "./" + relative(join(appDir, "src", "api"), filePath).split(sep).join("/");
    importLines.push(`import * as ${importName} from "${importPath}";`);
    entries.push(`  { pattern: ${JSON.stringify(patternForFile(filePath))}, module: ${importName} },`);
  });

  const content = [
    "// AUTO-GENERATED by scripts/genApiRoutes.ts. Do not edit by hand.",
    'import type { ApiRouteModule } from "./server/types.ts";',
    "",
    ...importLines,
    "",
    "export const generatedRoutes: { pattern: string; module: ApiRouteModule }[] = [",
    ...entries,
    "];",
    "",
  ].join("\n");

  await writeFile(outputFile, content);
  console.log(`Generated ${files.length} API routes into ${relative(process.cwd(), outputFile)}`);
}

await main();
