/** Build the native JavaScript runtime and generate its static Bun loader. */

import { existsSync } from "node:fs";
import { copyFile, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { $ } from "bun";

const here = import.meta.dir;
const outDir = join(here, "../../src/exec/native");
const args = process.argv.slice(2);
const debug = args.includes("--debug");

function flagValue(name: string): string | undefined {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}

const rustTarget = flagValue("--target");
const destPlatform = flagValue("--dest-platform") ?? process.platform;
const destArch = flagValue("--dest-arch") ?? process.arch;
const buildDirName = "generated";
const buildDir = join(here, buildDirName);
await mkdir(buildDir, { recursive: true });

const napiArgs = ["build", "--output-dir", buildDirName, "--no-js"];
if (!debug) napiArgs.push("--release");
if (rustTarget) napiArgs.push("--target", rustTarget);

console.log(`[native-exec] napi ${napiArgs.join(" ")}`);
await $`bunx napi ${napiArgs}`.cwd(here);

const built = join(buildDir, "exec.node");
if (!existsSync(built)) {
  throw new Error(`[native-exec] expected build output not found at ${built}`);
}

const destName = `exec-${destPlatform}-${destArch}.node`;
const dest = join(outDir, destName);
await mkdir(dirname(dest), { recursive: true });
await rm(dest, { force: true });
await copyFile(built, dest);
console.log(`[native-exec] → ${dest}`);

await writeFile(
  join(outDir, "addon.ts"),
  `// Generated by native/exec/build.ts — do not edit.\nexport const nativeExec = require("./${destName}");\n`,
);
