import { createHmac, timingSafeEqual } from "node:crypto";
import { config } from "../config.ts";

type ParsedJobToken = {
  timestamp: string;
  userId: string | null;
};

function createSignature(spaceId: string, timestamp: string, userPart?: string): string {
  const payload =
    userPart === undefined
      ? `${spaceId}:${timestamp}`
      : `${spaceId}:${timestamp}:${userPart}`;
  return createHmac("sha256", config().AUTH_SECRET ?? "")
    .update(payload)
    .digest("hex");
}

function safeSigEquals(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  return timingSafeEqual(Buffer.from(a), Buffer.from(b));
}

/** Create an HMAC job token scoped to a spaceId and userId. Valid for 1 hour. */
export function createJobToken(
  spaceId: string,
  timestamp: string,
  userId?: string | null,
): string {
  const userPart = userId ? Buffer.from(userId, "utf8").toString("base64url") : "-";
  return `${timestamp}.${userPart}.${createSignature(spaceId, timestamp, userPart)}`;
}

/** Verify an HMAC job token generated by createJobToken. */
export function verifyJobToken(token: string, spaceId: string): boolean {
  return parseJobToken(token, spaceId) !== null;
}

/** Parse and verify an HMAC job token generated by createJobToken. */
export function parseJobToken(token: string, spaceId: string): ParsedJobToken | null {
  const parts = token.split(".");
  if (parts.length !== 2 && parts.length !== 3) return null;

  const timestamp = parts[0];
  const ts = parseInt(timestamp, 10);
  if (!Number.isFinite(ts)) return null;
  const age = Date.now() - ts;
  if (age < 0 || age > 3_600_000) return null;

  // Legacy token format: <timestamp>.<sig>
  if (parts.length === 2) {
    const sig = parts[1];
    const expected = createSignature(spaceId, timestamp);
    if (!safeSigEquals(sig, expected)) return null;
    return { timestamp, userId: null };
  }

  const userPart = parts[1];
  const sig = parts[2];
  const expected = createSignature(spaceId, timestamp, userPart);
  if (!safeSigEquals(sig, expected)) return null;

  let userId: string | null = null;
  if (userPart !== "-") {
    try {
      userId = Buffer.from(userPart, "base64url").toString("utf8");
    } catch {
      return null;
    }
  }

  return { timestamp, userId };
}
