import { createHmac, timingSafeEqual } from "node:crypto";
import { config } from "../config.ts";

/** Create an HMAC job token scoped to a spaceId. Valid for 1 hour. */
export function createJobToken(spaceId: string, timestamp: string): string {
  return (
    timestamp +
    "." +
    createHmac("sha256", config().AUTH_SECRET ?? "")
      .update(spaceId + ":" + timestamp)
      .digest("hex")
  );
}

/** Verify an HMAC job token generated by createJobToken. */
export function verifyJobToken(token: string, spaceId: string): boolean {
  const dot = token.indexOf(".");
  if (dot === -1) return false;
  const timestamp = token.slice(0, dot);
  const sig = token.slice(dot + 1);
  const age = Date.now() - parseInt(timestamp, 10);
  if (age < 0 || age > 3_600_000) return false;
  const expected = createHmac("sha256", config().AUTH_SECRET ?? "")
    .update(spaceId + ":" + timestamp)
    .digest("hex");
  return timingSafeEqual(Buffer.from(sig), Buffer.from(expected));
}
