import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

const appDir = join(import.meta.dir, "..");
const clientDir = join(appDir, "dist/client");
const outputFile = join(appDir, "src/generated/client-assets.ts");

export async function collectClientAssetFiles(
  directory: string,
): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name.startsWith(".")) {
      continue;
    }

    const fullPath = join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectClientAssetFiles(fullPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(fullPath);
    }
  }

  return files;
}

export async function generateClientAssetsModule() {
  try {
    await readdir(clientDir);
  } catch {
    throw new Error(`Client build output not found at ${clientDir}`);
  }

  const files = (await collectClientAssetFiles(clientDir)).sort();
  const importLines: string[] = [];
  const mapEntries: string[] = [];

  for (const [index, filePath] of files.entries()) {
    const importName = `asset${index}`;
    const importPath = relative(dirname(outputFile), filePath).split(sep).join("/");
    const publicPath = `/${relative(clientDir, filePath).split(sep).join("/")}`;

    importLines.push(
      `import ${importName} from "${importPath}" with { type: "file" };`,
    );
    mapEntries.push(`  ["${publicPath}", ${importName}]`);
  }

  const content = [
    "// Generated by scripts/generate-client-assets.ts. Do not edit.",
    ...importLines,
    "",
    "export const embeddedClientAssets = new Map<string, string>([",
    ...mapEntries.map((entry) => `${entry},`),
    "]);",
    "",
  ].join("\n");

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, content);
}

await generateClientAssetsModule();
