#!/usr/bin/env bun
/**
 * Freezes the OpenAPI document — the route registry plus each handler's own
 * doc comments — into `generated/openapi.ts`, embedded in the compiled binary
 * the same way `build.ts` embeds the client assets. Run by `task compile`,
 * before `bun build --compile`, while the route files this reads still exist
 * as plain source on disk.
 *
 * Dev and test runs never call this: `#api/routes/openapi.ts` reads the same
 * doc comments live in that mode, so the schema always matches what is on
 * disk without a build step in the loop.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadRouteDocs } from "#api/openapi/discover.ts";
import { buildOpenApiDocument } from "#api/openapi/document.ts";
import { apiRoutes } from "#api/routes.ts";

export async function generateOpenApiModule(): Promise<void> {
  const routeDocs = await loadRouteDocs();
  const document = buildOpenApiDocument(apiRoutes, routeDocs);

  const outputFile = join(import.meta.dir, "../generated/openapi.ts");
  const content = [
    "// Generated by scripts/generate-openapi.ts. Do not edit.",
    `export const embeddedOpenApiSchema = ${JSON.stringify(document, null, 2)} as const;`,
    "",
  ].join("\n");

  await mkdir(join(import.meta.dir, "../generated"), { recursive: true });
  await writeFile(outputFile, content);
}

if (import.meta.main) {
  await generateOpenApiModule();
  console.log("[openapi] generated/openapi.ts written");
}
